name: UI Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["16.13.2"]
        npm-version: ["8.5.1"]

    defaults:
      run:
        working-directory: ./src/tauri

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Run svelte-check
      run: npm run check

    - name: Check formatting with prettier
      run: npm run format-check

