name: UI Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        node-version: ["16.13.2"]
        npm-version: ["8.5.1"]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./src/tauri

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Determine npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - name: Restore npm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}

    - name: Run svelte-check
      run: |
        npm run check

    - name: Check formatting with prettier
      run: |
        npm run format-check

